### ISSUE TITLE
Force SI units?

### ISSUE THREAD

**Issue by sesh** [Leftium/ultra-weather#1]
Is there a way to force the page to display in SI units? One of the README screenshots displays degrees Celsius, but I can’t see how to switch.

**Comment by Leftium** [comment]
I forgot to document that feature: C/F display can be toggled by tapping the large temperature display (portrait mode) or the city name (landscape mode).

There is also a request to add a URL option, which may be added in the future.

**Comment by sesh** [comment]
Great! A way to do this with a URL parameter would be great for bookmarking.
